---
- name: Update sources mirrors
  replace:
    path: /etc/apt/sources.list
    regexp: http://([A-Za-z0-9-]+\.)?archive\.ubuntu\.com/
    replace: http://{{ubuntu_mirror_country}}.archive.ubuntu.com/


- name: System Update
  apt:
    update_cache: yes
    upgrade: full
  notify: check_reboot

- name: Set Hostname
  shell: hostname {{ hostname }} && echo {{ hostname }} > /etc/hostname && sed -i '/127\.0\.1\.1/c\127.0.1.1 {{ hostname }}' /etc/hosts

- name: Create groups
  group:
    name: "{{ item }}"
  loop: "{{ machine_groups }}"

- name: Create users
  user:
    name: "{{ item.name }}"
    groups: "{{ item.groups | default([]) }}"
    password: "{{ item.password | default('') | password_hash('sha512', item.salt | default ('')) }}"
    shell: "{{ '/bin/bash' if item.password is defined else '/usr/sbin/nologin' }}"
  loop: "{{ machine_users }}"
  no_log: True