---

- name: System Update
  apt:
    update_cache: yes
    upgrade: full
  notify: check_reboot

- name: Set Hostname
  shell: hostname {{ hostname }} && echo {{ hostname }} > /etc/hostname && sed -i '/127\.0\.1\.1/c\127.0.1.1 {{ hostname }}' /etc/hosts