---
- name: Check Reboot
  ansible.builtin.shell: "[ -f /var/run/reboot-required ]"
  failed_when: false
  register: reboot_required
  changed_when: reboot_required.rc == 0
  notify: Reboot

- name: Reboot
  ansible.builtin.reboot:
